### PR TITLE
Tickets/dm 9481

### PR DESCRIPTION
**Pull request by daues**

### CODE REVIEW

**Comment by timj** [comment]
Can some of these commits be squashed? What's the merge from master onto the ticket branch doing?

**Comment by daues** [comment]
The pull request #112 page was declaring that  it was necessary to merge changes that 
had been made on master to the ticket before proceeding, i.e., before  merging the dm 9481 changes to master.

**Comment by timj** [comment]
That's github telling you there have been changes on master that can't be tested I think. The project development policy is to rebase branches to master rather than merge master to the branch. Continually merging master to the branch leads to a history that looks a bit confusing.

See https://developer.lsst.io/processes/workflow.html#review-preparation

This assumes that the developer guide git repository follows standard practice for DM (which I assumed it did).

**Comment by daues** [comment]
The Squash & Merge option was attempted, and it looks like a single commit  b9267ac was merged.

**Comment by timj** [comment]
Yes. It also doesn't have a merge commit. We generally don't use the Github merge button unless there are the specific circumstances of the branch commits being on the tip of master and all ready to merge. Rebasing has to happen on the client end first.

**Comment by daues** [comment]
If the not-rebased-commits are already remote, then is it too late to 
follow the procedure 
...
git rebase -i master
# interactive rebase
git push --force
...

Or will all be well ?

**Comment by timj** [comment]
You are always allowed to force push a ticket branch. You are not allowed to force push master.

**Pull request merged**
