### PR TITLE
added 2 useful jira tips

### PR DESCRIPTION
**Pull request by jbecla**

### CODE REVIEW

**Comment by jonathansick** [comment]
Hi @jbecla this is great. Do you need sign-off before merging? I don't see any issue here.

**Comment by timj** [comment]
Is this in limbo waiting for @ktlim to approve it? Seems uncontroversial.

**Comment by ktlim** [comment]
Not waiting on me, AFAIK.  No ticket is evident, so no review requested.

**Comment by timj** [comment]
I merged this as it seemed uncontroversial and everyone was waiting on everyone else.

**Pull request merged**
