### PR TITLE
lsst-dev: note that xpra requires py2

### PR DESCRIPTION
**Pull request by PaulPrice**
At least two people have hit this subtlety in the last couple of weeks.

### CODE REVIEW

**Comment by PaulPrice** [comment]
Rendered at: https://developer.lsst.io/v/u-price-20171221/services/lsst-dev.html#configure-remote-display-with-xpra

**Comment by PaulPrice** [comment]
Except the error doesn't show up.... Lemme fix that.

**Comment by PaulPrice** [comment]
Better. OK, @jonathansick, have at it!

**Comment by PaulPrice** [comment]
Done.

**Comment by jonathansick** [comment]
Doh, I typo'd the "Python" in my suggested fix; sorry! Could you fix that and then go ahead with the merge.

**Pull request merged**
