### PR TITLE
DM-35388: Fix dev guide links in "tune your shell for git"

### PR DESCRIPTION
**Pull request by parejkoj**
The rendered version: https://developer.lsst.io/v/DM-35388/git/setup.html#tune-your-shell-for-git

### CODE REVIEW

**Review by bsmartradio — APPROVED** [review]
Comments are helpful at explaining how to install the changes.

**Review by erinleighh — CHANGES_REQUESTED** [review]
Links go where they say they're going to go and the expanded descriptions are helpful, however the numbers are off (skipped 2. and went from 1. to 3.) and is no longer automatically formatting as a list.

**Comment by parejkoj** [comment]
Good catch on the skipped number and broken list, @erinleighh . I made a tweak after @bsmartradio looked at it, and apparently broke it then. Should be fixed now.

**Review by erinleighh — APPROVED** [review]
Fix looks great!

**Pull request merged**
